name: CI/CD Pipeline

on: [push]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Start PostgreSQL container
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: JAR Staging Area
        run: mkdir staging && cp target/*.jar staging

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging/spring-data-jpa-0.0.1-SNAPSHOT.jar

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down

